platform :ios, "7.0"

pod 'CocoaAsyncSocket'
pod 'MBProgressHUD' , :git => 'https://github.com/jdg/MBProgressHUD.git'
pod 'CocoaLumberjack'
pod 'AFNetworking'
pod 'Reachability'
pod 'TWMessageBarManager', '~> 1.7.0'
pod 'PNChart', '~> 0.5'
pod 'EAIntroView', '~> 2.6.0'
pod 'NSDate+Calendar'
pod 'HexColors'
pod 'SGNavigationProgress'
pod 'EGOTableViewPullRefresh'
pod 'FMDB'
pod 'Toast', '~> 2.3'
pod 'MJPopupViewController'
pod 'DDProgressView'
pod 'NCICharts'
pod 'CRToast', '~> 0.0.7'
pod 'BEMSimpleLineGraph'